In [103]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
import time
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [70]:
df = pd.read_csv("https://raw.githubusercontent.com/kb22/Heart-Disease-Prediction/refs/heads/master/dataset.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [71]:
df.info()
df["target"].unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


array([1, 0], dtype=int64)

In [72]:
X = df.drop("target", axis=1)
y = df["target"]                 #splitting

In [73]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.3,random_state=42)    #train test split

In [74]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)              #scaling

In [75]:
log_clf = LogisticRegression()
dt_clf = DecisionTreeClassifier()
svc_clf = SVC(probability=True)           #MODELS

In [76]:
voting_clf = VotingClassifier(estimators=[
    ('log_reg', log_clf),
    ('dt', dt_clf),
    ('svc', svc_clf)
], voting='soft')                           #soft voting

In [77]:
start_time = time.time()
voting_clf.fit(X_train_scaled , y_train)

VotingClassifier(estimators=[('log_reg', LogisticRegression()),
                             ('dt', DecisionTreeClassifier()),
                             ('svc', SVC(probability=True))],
                 voting='soft')

In [78]:
training_time = time.time() - start_time
start_time = time.time()

In [79]:
y_pred = voting_clf.predict(X_test_scaled)
prediction_time = time.time() - start_time

In [80]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(accuracy)
print(precision)
print(recall)
print(f1)
print("Confusion Matrix:")
print(conf_matrix)
print(f"Time taken for training: {training_time:.4f} seconds")
print(f"Time taken for prediction: {prediction_time:.4f} seconds")

0.7793427230046949
0.8349514563106796
0.7413793103448276
0.7853881278538812
Confusion Matrix:
[[80 17]
 [30 86]]
Time taken for training: 1.0011 seconds
Time taken for prediction: 1.0000 seconds


In [81]:
voting_clf_hard = VotingClassifier(estimators= [ ('log_reg', log_clf),
    ('dt', dt_clf),
    ('svc', svc_clf)], voting='hard')                                    #HARD VOTING

In [82]:
start_time = time.time()
voting_clf_hard.fit(X_train_scaled,y_train)

VotingClassifier(estimators=[('log_reg', LogisticRegression()),
                             ('dt', DecisionTreeClassifier()),
                             ('svc', SVC(probability=True))])

In [83]:
training_time = time.time() - start_time
start_time = time.time()

In [84]:
y_pred_hard = voting_clf_hard.predict(X_test_scaled)
prediction_time = time.time() - start_time

In [85]:
accuracy = accuracy_score(y_test, y_pred_hard)
precision = precision_score(y_test, y_pred_hard)
recall = recall_score(y_test,  y_pred_hard)
f1 = f1_score(y_test,  y_pred_hard)
conf_matrix = confusion_matrix(y_test,  y_pred_hard)

print(accuracy)
print(precision)
print(recall)
print(f1)
print("Confusion Matrix:")
print(conf_matrix)

print(f"Time taken for training: {training_time:.4f} seconds")
print(f"Time taken for prediction: {prediction_time:.4f} seconds")

0.8215962441314554
0.825
0.853448275862069
0.8389830508474576
Confusion Matrix:
[[76 21]
 [17 99]]
Time taken for training: 0.6747 seconds
Time taken for prediction: 0.8288 seconds


In [86]:
gb_clf = GradientBoostingClassifier(random_state=42)    #BOOSTING

In [ ]:
start_time = time.time()
gb_clf.fit(X_train_scaled, y_train)                      #TRAINING 
training_time = time.time() - start_time

In [87]:
start_time = time.time()                                     
y_pred = gb_clf.predict(X_test_scaled)                    #PREDICTION
prediction_time = time.time() - start_time

In [88]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(accuracy)
print(precision)
print(recall)
print(f1)
print("Confusion Matrix:")
print(conf_matrix)

print(f"Time taken for training: {training_time:.4f} seconds")
print(f"Time taken for prediction: {prediction_time:.4f} seconds")

0.7746478873239436
0.7786885245901639
0.8189655172413793
0.7983193277310925
Confusion Matrix:
[[70 27]
 [21 95]]
Time taken for training: 0.1166 seconds
Time taken for prediction: 0.0020 seconds


In [99]:
bagging_clf = BaggingClassifier(estimator=dt_clf, n_estimators=50, random_state=42)  #BAGGING

In [100]:
start_time = time.time()
bagging_clf.fit(X_train_scaled,y_train)           #TRAINING
training_time =  time.time() - start_time         

In [101]:
start_time = time.time()
y_pred_bag = bagging_clf.predict(X_test_scaled)    #PREDICTION
predict_time = time.time() - start_time

In [102]:
accuracy = accuracy_score(y_test,y_pred_bag)
precision = precision_score(y_test,y_pred_bag)
f1 = f1_score(y_test,y_pred_bag)
conf_mat = confusion_matrix(y_test,y_pred_bag)

print(accuracy)
print(precision)
print(recall)
print(f1)
print("Confusion Matrix:")
print(conf_matrix)

print(f"Time taken for training: {training_time:.4f} seconds")
print(f"Time taken for prediction: {prediction_time:.4f} seconds")

0.7652582159624414
0.7844827586206896
0.8189655172413793
0.7844827586206896
Confusion Matrix:
[[70 27]
 [21 95]]
Time taken for training: 0.0994 seconds
Time taken for prediction: 0.0020 seconds


In [104]:
base_learners = [
    ('dt', DecisionTreeClassifier(random_state=42)),
    ('svc', SVC(probability=True, random_state=42)),
    ('log_reg', LogisticRegression(random_state=42))                #STACKING
]
meta_model = LogisticRegression(random_state=42) 

In [107]:
stack_clf = StackingClassifier(estimators = base_learners, final_estimator = meta_model)

In [109]:
start_time= time.time()
stack_clf.fit(X_train_scaled,y_train)
training_time = time.time()-start_time

In [112]:
start_time = time.time()
y_pred_stack = stack_clf.predict(X_test_scaled)
prediction_time = time.time() - start_time

In [114]:
accuracy = accuracy_score(y_test,y_pred_stack)
precision = precision_score(y_test,y_pred_stack)
f1 = f1_score(y_test,y_pred_stack)
conf_mat = confusion_matrix(y_test,y_pred_stack)

print(accuracy)
print(precision)
print(recall)
print(f1)
print("Confusion Matrix:")
print(conf_matrix)

print(f"Time taken for training: {training_time:.4f} seconds")
print(f"Time taken for prediction: {prediction_time:.4f} seconds")

0.8028169014084507
0.8245614035087719
0.8189655172413793
0.8173913043478261
Confusion Matrix:
[[70 27]
 [21 95]]
Time taken for training: 0.0623 seconds
Time taken for prediction: 0.0040 seconds
